# version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/arm64/v8
    container_name: 2_database-mssql-1

    environment:
      SA_PASSWORD: "Lasagna_321"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

    volumes:
      - ./data:/var/opt/mssql/data 
